---
- name: Deploy Flask App on EC2
  hosts: all
  become: yes

  tasks:
    # 1️⃣ Pull the latest image from Docker Hub
    - name: Pull latest Docker image
      command: docker pull "{{ lookup('env', 'DOCKER_USERNAME') }}/issue-tracker:latest"

    # 2️⃣ Stop and remove old container
    - name: Stop and remove old container
      shell: |
        docker ps -a --format '{{ '{{' }} .Names {{ '}}' }}' | grep -w issue-tracker-app && docker stop issue-tracker-app && docker rm issue-tracker-app || true
      ignore_errors: yes

    # 3️⃣ Start Flask container
    - name: Run Flask app container
      command: >
        docker run -d --name issue-tracker-app
        -p 8080:5000
        --network issue-tracker-network
        -e DB_HOST={{ secrets.DB_HOST }}
        -e DB_PORT=3306
        -e DB_NAME="{{ secrets.DB_NAME }}"
        -e DB_USER="{{ secrets.DB_USER }}"
        -e DB_PASSWORD="{{ secrets.DB_PASSWORD }}"
        "{{ lookup('env', 'DOCKER_USERNAME') }}/issue-tracker:latest"

    # 4️⃣ Restart Nginx
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted