---
- name: Deploy Flask App on EC2
  hosts: all
  become: yes

  tasks:
    # 1️⃣ Pull the latest image from Docker Hub
    - name: Pull latest Docker image
      command: docker pull "{{ secrets.DOCKER_USERNAME }}/issue-tracker:latest"

    # 2️⃣ Stop and remove old container
    - name: Stop and remove old container
      command: docker stop issue-tracker-app && docker rm issue-tracker-app
      ignore_errors: yes

    # 3️⃣ Start Flask container
    - name: Run Flask app container
      command: >
        docker run -d --name issue-tracker-app
        -p 80:5000
        --network issue-tracker-network
        -e DB_HOST=issue-tracker-db
        -e DB_PORT=3306
        -e DB_NAME=issue_tracker
        -e DB_USER=laravel
        -e DB_PASSWORD=securepassword
        "{{ secrets.DOCKER_USERNAME }}/issue-tracker:latest"

    # 4️⃣ Restart Nginx
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted